language: python
matrix:
    include:
        - python: 3.4
        - python: 3.5
        - python: 3.6
install:
    - pip install -r test_requirements.txt
script:
    - flake8 . --count
    - coverage run --source=test,lib -m unittest

after_success:
    - coverage report -m
    - coveralls
