language: python

python: 3.6

matrix:
  include:
    - os: linux
      language: python
      include:
        python: 3.4
        python: 3.5
        python: 3.6
      before_install:
        - pip install -r test_requirements.txt
      script:
        - flake8 lib test --count
        - coverage run --source=test,lib -m unittest
        - namanager -s third_party/namanager_settings.json --require --count
      after_success:
        - coverage report -m
        - coveralls

    - os: linux
      language: cpp
      script:
        ./script/test_cpp.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
